spring:
  redis:
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    host: localhost:8080
    port: 6379
    password: ''


    # application.yml
    fcm:
      key:
        path: gjgs-fcm.json
        scope: https://www.googleapis.com/auth/cloud-platform